#!/bin/bash

MONITOR="DP-0"
TARGET_WORKSPACES=("4" "5" "6")

# Твои значения из прошлых экспериментов
BRIGHTNESS_DARK="0.24"
GAMMA_DARK="0.5:0.5:0.6"

# Получаем текущие настройки 
BRIGHTNESS_DEFAULT="1.0" 
GAMMA_DEFAULT="1.0:1.0:1.0" 

#echo "Исходная яркость: $CURRENT_BRIGHTNESS"
#echo "Исходная гамма: $CURRENT_GAMMA"

# Функция для применения яркости и гаммы
#set_monitor() {
#    local brightness="$1"
#    local gamma="$2"
#    xrandr --output "$MONITOR" --brightness "$brightness" --gamma "$gamma"
#}

# Бесконечный цикл: отслеживаем активный workspace
while true; do
    ACTIVE_WS=$(i3-msg -t get_workspaces | jq -r '.[] | select(.focused == true).name')


    if [[ " ${TARGET_WORKSPACES[@]} " =~ " ${ACTIVE_WS} " ]]; then
        xrandr --output "$MONITOR" --brightness "$BRIGHTNESS_DEFAULT" --gamma "$GAMMA_DEFAULT"
    else
        xrandr --output "$MONITOR" --brightness "$BRIGHTNESS_DARK" --gamma "$GAMMA_DARK"
    fi

    # Ждём немного между проверками
    sleep 0.5
done
